src/Entity/RobotHumain.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RobotHumainRepository")
 */
class RobotHumain
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $SerialNumber;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Surname;

    /**
     * @ORM\OneToMany(targetEntity="UselessEntity", mappedBy="robotHumain")
     */
    private $uselessEntities;

    public function __construct() {
    	$this->$uselessEntities = new ArrayCollection();
     $this->uselessEntities = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSerialNumber(): ?int
    {
        return $this->SerialNumber;
    }

    public function setSerialNumber(int $SerialNumber): self
    {
        $this->SerialNumber = $SerialNumber;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->Surname;
    }

    public function setSurname(string $Surname): self
    {
        $this->Surname = $Surname;

        return $this;
    }

    /**
     * @return Collection|UselessEntity[]
     */
    public function getUselessEntities(): Collection
    {
        return $this->uselessEntities;
    }

    public function addUselessEntity(UselessEntity $uselessEntity): self
    {
        if (!$this->uselessEntities->contains($uselessEntity)) {
            $this->uselessEntities[] = $uselessEntity;
            $uselessEntity->setRobotHumain($this);
        }

        return $this;
    }

    public function removeUselessEntity(UselessEntity $uselessEntity): self
    {
        if ($this->uselessEntities->contains($uselessEntity)) {
            $this->uselessEntities->removeElement($uselessEntity);
            // set the owning side to null (unless already changed)
            if ($uselessEntity->getRobotHumain() === $this) {
                $uselessEntity->setRobotHumain(null);
            }
        }

        return $this;
    }
}

src/Entity/UselessEntity.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UselessEntityRepository")
 */
class UselessEntity
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $string;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datetime;

    /**
     * @ORM\Column(type="boolean")
     */
    private $boolean;

    /**
     * @ORM\Column(type="integer")
     */
    private $integer_value;

    /**
     * @ORM\ManyToOne(targetEntity="RobotHumain", inversedBy="uselessEntities")
     * @ORM\JoinColumn(name="robot_humain_id", referencedColumnName="id")
     */
    private $robotHumain;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getString(): ?string
    {
        return $this->string;
    }

    public function setString(string $string): self
    {
        $this->string = $string;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getDatetime(): ?\DateTimeInterface
    {
        return $this->datetime;
    }

    public function setDatetime(\DateTimeInterface $datetime): self
    {
        $this->datetime = $datetime;

        return $this;
    }

    public function getBoolean(): ?bool
    {
        return $this->boolean;
    }

    public function setBoolean(bool $boolean): self
    {
        $this->boolean = $boolean;

        return $this;
    }

    public function getIntegerValue(): ?int
    {
        return $this->integer_value;
    }

    public function setIntegerValue(int $integer_value): self
    {
        $this->integer_value = $integer_value;

        return $this;
    }

    public function getRobotHumain(): ?RobotHumain
    {
        return $this->robotHumain;
    }

    public function setRobotHumain(?RobotHumain $robotHumain): self
    {
        $this->robotHumain = $robotHumain;

        return $this;
    }
}

src/Form/UselessEntityType.php
<?php

namespace App\Form;

use App\Entity\UselessEntity;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;


class UselessEntityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
		->add('string', TextType::class)
		->add('text', TextareaType::class)
		->add('datetime', DateTimeType::class)
		->add('boolean', CheckboxType::class)
		->add('integerValue', IntegerType::class)
		->add('save', SubmitType::class, ['label' => 'save this important work'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => UselessEntity::class,
        ]);
    }
}

src/Controller/UselessEntityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\UselessEntity;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use App\Form\UselessEntityType;


class UselessEntityController extends AbstractController
{
    /**
	 * @Route ("/useless", name = "uselessEntityIndex")
	 * @Route ("/useless/sort-by-{sortAttr}-{sortDir}", name = "uselessEntityIndexSorted", requirements = { "sortDir" = "asc|desc", "sortAttr" = "id|string|text|datetime|boolean|integer_value" } )
	 * //Route ("/useless/filter/{filterAttr}/{filterOper}/{filterArg}", name = "uselessEntityIndexFiltered" requirements = { "filterOper" = "eq|gt|gteq|lt|lteq", "filterAttr" = "id|string|text|datetime|boolean|integer_value" })
	 */
    public function listUselessAction($sortAttr = "id", $sortDir = "asc")
    {
		$filters = 
		$uselessEntities = $this->getDoctrine()->getRepository(UselessEntity::class)->findBy(array(), [ $sortAttr => $sortDir ]);
					
        return $this->render('useless_entity/index.html.twig', [
            'useless_entities' => $uselessEntities,
        ]);
    }

    /**
     * @Route("/useless/{id}", name="uselessEntityShow", requirements = { "id" = "\d+" } )
     *
     */
    public function uselessEntityShowAction(UselessEntity $uselessEntity)
    {
		return $this->render('useless_entity/show.html.twig', [
		'useless_entity' => $uselessEntity,
		'deleteButton' => $this->createDeleteForm($uselessEntity)->createView(),
		]);
    }

    /**
     * @Route("/useless/new/old", name="uselessEntityNewActionOld" )
     */

    public function old_uselessEntityNewAction(Request $request) {
	    $newUseless = new UselessEntity();
	    $form = $this->createFormBuilder($newUseless)
		->add('string', TextType::class)
		->add('text', TextareaType::class)
		->add('datetime', DateTimeType::class)
		->add('boolean', CheckboxType::class)
		->add('integerValue', IntegerType::class)
		->add('save', SubmitType::class, ['label' => 'save this important work'])
		->getForm();

	    $form->handleRequest($request);
	    if($form->isSubmitted() && $form->isValid()) {
		    $m = $this->getDoctrine()->getManager();
		    $m->persist($newUseless);
		    $m->flush();
		    return $this->redirectToRoute('uselessEntityShow', [ 'id' => $newUseless->getId() ]);
	    } else {
	    	return $this->render('useless_entity/new.html.twig', [ 'form' => $form->createView() ]);
	    }
    }	

    /**
     * @Route("/useless/new", name="uselessEntityNewAction")
     *
     */	

     public function uselessEntityNewAction(Request $request) {
	    $newUseless = new UselessEntity();
	    $form = $this->createForm(UselessEntityType::class, $newUseless);
     	$form->handleRequest($request);
	    if($form->isSubmitted() && $form->isValid()) {
		    $m = $this->getDoctrine()->getManager();
		    $m->persist($newUseless);
		    $m->flush();
		    return $this->redirectToRoute('uselessEntityShow', [ 'id' => $newUseless->getId() ]);
	    } else {
	    	return $this->render('useless_entity/new.v2.html.twig', [ 'form' => $form->createView() ]);
	    }
     }
	
    /**
     * @Route("/useless/update/{id}", name="uselessEntityUpdateAction", requirements = { "id" = "\d+" } )
     *
     */	

     public function uselessEntityUpdateAction(Request $request, UselessEntity $uselessEntity) {
	   
	    $form = $this->createForm(UselessEntityType::class, $uselessEntity);
     	$form->handleRequest($request);
	    if($form->isSubmitted() && $form->isValid()) {
		    $m = $this->getDoctrine()->getManager();
		    $m->persist($uselessEntity);
		    $m->flush();
		    return $this->redirectToRoute('uselessEntityShow', [ 'id' => $uselessEntity->getId() ]);
	    } else {
	    	return $this->render('useless_entity/new.v2.html.twig', [ 'form' => $form->createView() ]);
	    }
     }	
	
	    
	/*
     * Crée un formulaire pour supprimer un Article
    */
    private function createDeleteForm(UselessEntity $uselessEntity)
    {
        //on crée un formulaire
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('uselessEntity_delete', array('id' => $uselessEntity->getId())))
            ->setMethod('DELETE')
            ->add('delete entity ' . $uselessEntity->getString(), SubmitType::class)
            ->getForm()
        ;
    }
	
	/**
	* @Route("/useless/delete/{id}", name="uselessEntity_delete", requirements = { "id" = "\d+" })
	* @Route("/useless/{id}/delete", name="uselessEntity_deleteAlt", requirements = { "id" = "\d+" })
	* @Route("/useless/{id}", name="uselessEntity_deleteREST", requirements = { "id" = "\d+" }, methods = { "DELETE" }) //TODO: pas marche
	*/
	public function uselessEntityDeleteAction(Request $request, UselessEntity $uselessEntity) {
		$m = $this->getDoctrine()->getManager();
		$m->remove($uselessEntity);
		$m->flush();
		return $this->redirectToRoute('uselessEntityIndex');
	}
	
}	

templates/useless_entity/delete.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
	
	{{ form(form) }}

	
{% endblock %}

templates/useless_entity/index.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
	<table>
	<tr>
		<th>id  <a href="{{ path('uselessEntityIndexSorted', { 'sortAttr':'id', 'sortDir':'asc' } ) }}"> &#9757</a> <a href="{{ path('uselessEntityIndexSorted', { 'sortAttr':'id', 'sortDir':'desc' } ) }}">&#9759</a></th>
		<th>string <a href="{{ path('uselessEntityIndexSorted', { 'sortAttr':'string', 'sortDir':'asc' } ) }}">&#9757</a> <a href="{{ path('uselessEntityIndexSorted', { 'sortAttr':'string', 'sortDir':'desc' } ) }}">&#9759</a></th>
		<th>text <a href="{{ path('uselessEntityIndexSorted', { 'sortAttr':'text', 'sortDir':'asc' } ) }}">&#9757</a> <a href="{{ path('uselessEntityIndexSorted', { 'sortAttr':'text', 'sortDir':'desc' } ) }}">&#9759</a></th>
		<th>datetime <a href="{{ path('uselessEntityIndexSorted', { 'sortAttr':'datetime', 'sortDir':'asc' } ) }}">&#9757</a> <a href="{{ path('uselessEntityIndexSorted', { 'sortAttr':'datetime', 'sortDir':'desc' } ) }}">&#9759</a></th>
		<th>boolean <a href="{{ path('uselessEntityIndexSorted', { 'sortAttr':'boolean', 'sortDir':'asc' } ) }}">&#9757</a> <a href="{{ path('uselessEntityIndexSorted', { 'sortAttr':'boolean', 'sortDir':'desc' } ) }}">&#9759</a></th>
		<th>integer <a href="{{ path('uselessEntityIndexSorted', { 'sortAttr':'integer_value', 'sortDir':'asc' } ) }}">&#9757</a> <a href="{{ path('uselessEntityIndexSorted', { 'sortAttr':'integer_value', 'sortDir':'desc' } ) }}">&#9759</a></th>
		<th>liens</th>
		<th>RobotHumain</th>
	</tr>
	
	{% for useless_entity in useless_entities %}
	<tr>
		<td>{{ useless_entity.id }}</td>
		<td>{{ useless_entity.string }}</td>
		<td>{{ useless_entity.text }}</td>
		<td>{{ useless_entity.datetime|date("m/d/Y") }}</td>
		<td>{{ useless_entity.boolean ? 'True' : 'False' }}</td>
		<td>{{ useless_entity.integervalue }}</td>
		<td><a href="{{ path('uselessEntityShow', {'id': useless_entity.id }) }}">voir</a> ou </td>
		<td><a href="{{ path('uselessEntityUpdateAction', {'id': useless_entity.id }) }}">update</a> ou</td>
		<td><a href="{{ path('uselessEntity_delete', {'id': useless_entity.id }) }}">delete</a></td>
		{% if useless_entity.robotHumain != null %}
		<td>#{{ useless_entity.robotHumain.serialnumber }}: {{ useless_entity.robotHumain.name }} ({{ useless_entity.robotHumain.surname }})</td>
		{% endif %}
	</tr>
	{% endfor %}
	
	</table>
{% endblock %}

templates/useless_entity/new.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
	
	{{ form_start(form) }}
	{{ form_widget(form) }}
	{{ form_end(form) }}

	
{% endblock %}

templates/useless_entity/new.v2.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
	
	{{ form(form) }}

	
{% endblock %}

templates/useless_entity/show.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
	<h3>#{{ useless_entity.id}}: {{ useless_entity.string }}</h3>
		
	<p>{{ useless_entity.text }}</p>
	
	<p>
	Publié le {{ useless_entity.datetime|date("m/d/Y") }}.
	Public: {{ useless_entity.boolean ? 'Oui' : 'Non' }}.
	Like(s): {{ useless_entity.integervalue }}.
	</p>
	
	<p>{{ form(deleteButton) }}<br />
	<a href="{{ path('uselessEntityUpdateAction', {'id': useless_entity.id }) }}">update</a></p>
	
{% endblock %}